### ISSUE TITLE
DutyCycle to be updated at the end current PWM period

### ISSUE THREAD

**Issue by khoih-prog** [khoih-prog/ESP8266_PWM#2]
Original post from @ggmichael  in [Change Duty Cycle #1](https://github.com/khoih-prog/ESP8266_PWM/issues/1#issuecomment-1025139508)

> Thanks for this! Your library has fixed a problem I was having with inconsistent calibration, which I now think arose from the changing timing of the analogWrite pwm.
> 
> One more feature that would be nice would be to be able to command a duty cycle update to occur at the end of the next full period instead of immediately (as I think happens now). If you're trying to create a continuously variable mean output voltage, resetting the channel at a frequency that approaches the PWM frequency causes a bias towards whichever part of the duty cycle comes first. This wouldn't happen if the update occurred at the end of the cycle. It may be that there are other applications (long cycles) where you would prefer the update straight away. So perhaps a flag to set either mode.

**Comment by khoih-prog** [comment]
HI  @ggmichael

I'll publish a new release to add this **enhancement** within half an hour for you to test the new feature. Be ready.

Regards,

**Comment by khoih-prog** [comment]
Hi @ggmichael 

The new [**ESP8266_PWM releases v1.2.2**](https://github.com/khoih-prog/ESP8266_PWM/releases/tag/v1.2.2) has just been published. Your contribution is noted in [**Contributions and Thanks**](https://github.com/khoih-prog/ESP8266_PWM#contributions-and-thanks). Please test and verify the new feature is supported and working OK now.

The library is better and better everyday, thanks to **contributing users** like you, who spot bugs, test and request enhancements. We, the library writers, normally **can't never have enough time, knowledge and experience** to know all the use-cases in the world to add the new features.

Best Regards,

---

### Releases v1.2.2

1. DutyCycle to be optionally updated at the end current PWM period instead of immediately. Check [DutyCycle to be updated at the end current PWM period #2](https://github.com/khoih-prog/ESP8266_PWM/issues/2)

**Comment by ggmichael** [comment]
I can confirm that the new code gets rid of the 'glitch' on changing duty cycle - that's great - thanks. I think you're right that analogWrite() doesn't do this, but there's no harm in having a better implementation. (However, something is now causing the ESP8266 to reboot periodically - I have to check over my integration of the library)

**Comment by khoih-prog** [comment]
HI @ggmichael 

> However, something is now causing the ESP8266 to reboot periodically - I have to check over my integration of the library

If you still have that problem, I suggest you try these mods to see if it's any better

1. Increase ESP8266 clock to 160MHz from 80MHz, if not yet
2. Increase the `HW_TIMER_INTERVAL_US` from 20uS to higher, such as 30, 50, 100uS. For example 
[**ISR_Modify_PWM.ino**#L46](https://github.com/khoih-prog/ESP8266_PWM/blob/main/examples/ISR_Modify_PWM/ISR_Modify_PWM.ino#L46)

```
#define HW_TIMER_INTERVAL_US      50L
```

The reason is the ISR-based function `run()` now **take more time to process** (`double` accuracy, dutycycle check, etc.)

I'm thinking, in future releases, about letting users optionally select `double`, `float` or `uint32_t` for dutycycle / frequency / period, depending on the use-case.

**Comment by ggmichael** [comment]
Hi Khoi,

I got a previous version to work by back-integrating the main parts of your
new updates. I did use floats for the duty cycle instead of double (I think
double is more precision than you could ever need). The period remained
uint32_t (this also makes sense to me, since this is the actual count).
Frequency could also be a float, since it is always converted. So maybe
this is the reason. I'll try your new suggestions when I get a chance -
probably only next week.

**Comment by khoih-prog** [comment]
> I did use floats for the duty cycle instead of double (I think double is more precision than you could ever need). The period remained uint32_t (this also makes sense to me, since this is the actual count). Frequency could also be a float, since it is always converted. 

I agree with you and will make `float` for DC and Freq, period `uint32_t`. Sorry for to be too unreasonably aggressive.

Will have a new release within today.

**Comment by khoih-prog** [comment]
Hi @ggmichael 

Please test the new [**ESP8266_PWM releases v1.2.3**](https://github.com/khoih-prog/ESP8266_PWM/releases/tag/v1.2.3)

---

### Releases v1.2.3

1. Use `float` for `DutyCycle` and `Freq`, `uint32_t` for `period`. 
2. Optimize code by not calculation in ISR

**Comment by ggmichael** [comment]
I confirm that update works, and also fixes the reboot problem.

**Comment by khoih-prog** [comment]
Glad to know it's working better now, thanks to **your** contribution anyway.
