### ISSUE TITLE
calculate pwm resolution

### ISSUE THREAD

**Issue by mrdevis** [khoih-prog/ESP8266_PWM#3]
Hi, 
and thanks for the work you have done on this!
I have a small question as I am a little stuck here.
If I program a PWM frequency of say 100Hz, how would I be able to calculate the resolution of the pulse width? 
cheers

**Comment by khoih-prog** [comment]
The resolution is not determined and is not fixed value as this is hybrid ISR-based, not purely hardware-based PWM.
It depends on many factors such as settings, how many PWM channels you're using, ESP8266 speed, etc.

But the resolution can be guessed around ms, and can be OK with slow PWM, which is the purpose of this library.

It's easier for you to measure the resolution, if necessary for some purpose, by writing extra code to measure. Treat this as an exercise for you.

Good Luck,

**Comment by mrdevis** [comment]
Ok, thanks for your reply. So it was hard
        to figure that out for a reason then :)
    I will approach this differently then.
    Never too old for an exercise
      
    Cheerio
    Jeroen
      
    
      
    
    
    On 5/18/22 17:20, Khoi Hoang wrote:
    
    
      
      The resolution is not determined and is not fixed
        value as this is hybrid ISR-based, not purely hardware-based
        PWM.
        It depends on many factors such as settings, how many PWM
        channels you're using, ESP8266 speed, etc.
      But the resolution can be guessed around ms, and can
        be OK with slow PWM, which is the purpose of this library.
      It's easier for you to measure the resolution, if
        necessary for some purpose, by writing extra code to measure.
        Treat this as an exercise for you.
      Good Luck,
      —
        Reply to this email directly, view it on GitHub, or unsubscribe.
        You are receiving this because you authored the thread.Message
          ID: ***@***.***>
      [
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/khoih-prog/ESP8266_PWM/issues/3#issuecomment-1130156200",
"url": "https://github.com/khoih-prog/ESP8266_PWM/issues/3#issuecomment-1130156200",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
